language: go

go:
  - 1.12.5

env:
- GO111MODULE=on

install:
  - go get -t ./...
  - go get -u github.com/golang/lint/golint

script:
  - go vet ./...
  - go test -race ./...

after_script:
  - golint ./...
